### PR TITLE
reject invalid votes

### PR DESCRIPTION
**Pull request by bundacia**
Fix for https://github.com/LearnersGuild/game/issues/68.

I went back and forth about doing this validation in RocketChat vs the api and went with this partly because we're already doing other validation here and partly because it's a snappier interface and more efficient to do this client side. The price we pay is a little more logic in out RocketChat integration.

### CODE REVIEW

**Comment by jeffreywescott** [comment]
Unfortunately, this won't work.

It's possible that a vote will match the regex but will still be invalid. Until the worker runs, there's simply no way to know whether or not a particular goal is valid, since it does the GitHub API validation at that point. If we try to do this client-side, we would need to put an API call to GitHub in the request / response cycle, which is not a good idea.

Furthermore, I can imagine other user interfaces for voting, perhaps from the UI panel itself.

The way I was planning to solve this was to add a field to each vote called `state` that would start as `PENDING` and flip to either `REJECTED` or `CONFIRMED`.

When the GraphQL API gets invoked, it would move the current `goals` array to something like `previousGoals`.

If the job runs and determines that the vote is invalid, it would move `goals` to `rejectedGoals`, move `previousGoals` to `goals`, and notify the user (via web socket) that their previous vote remains in tact.

**Comment by bundacia** [comment]
Yeah, that makes sense. Still, for stuff that we know will fail (like non-numeric goal ids, or trying to vote for 3 goals at once) we could provide a snappier interface by just rejecting them immediately.

**Comment by jeffreywescott** [comment]
We should discuss. I think getting multiple error messages is less friendly than getting a single error message a few milliseconds later. But perhaps I could be convinced.

**Comment by jeffreywescott** [comment]
Closing in lieu of a server-side solution.

**Pull request closed without merging**
